### ISSUE TITLE
Variance of gradient noise and optimal learning rate

### ISSUE THREAD

**Issue by devmotion** [wjmaddox/swa_gaussian#1]
Hej!

Maybe I'm wrong, but I think you use an incorrect formula for computing the optimal learning rate in https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/grad_cov/grad_cov_utils.py#L52. From the first equation in Appendix A of your paper (which is Eq. 6 in Mandt's paper) it follows that

V(ĝ(θ)) ≈ V(∇g(θ) / √B) = V(∇g(θ)) / B = C(θ) / B,

which seems to be mentioned by Mandt in Assumption 1 as well. Thus you can estimate C by estimating V (ĝ(θ)) and multiplying with B, and the optimal learning rate according to Mandt is given by

η = 2 B d / (N tr(C(θ))) ≈ 2 B d / (N tr(B V(ĝ(θ)))) = 2 d / (N tr(V(ĝ(θ))).

To me it seems that your estimate for the optimal learning is off by a factor of B². This means that the minimum optimal learning rate of 3000 that you report in the appendix should actually be 3000 / 128² ≈ 0.18 (assuming you used the default batch size of 128 in https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/grad_cov/run_grad_cov.py#L23), which would be much closer to a standard learning rate of 0.1.

As I said, maybe I'm getting something completely wrong, so I'd be happy to hear how you obtain the formula in Appendix A and https://github.com/wjmaddox/swa_gaussian/blob/master/experiments/grad_cov/grad_cov_utils.py#L52.

**Comment by wjmaddox** [comment]
Hi, 

Thanks for carefully reading our paper! We just went through and determined out that your understanding of the formula is correct. We'll post a correction to both the code and arxiv soon (actually the code doesn't include the momentum correction and we had to correct that manually ourselves).

One point is that the minimum optimal learning rate we report should be 30,000 from the Figure 4 in the Appendix (a small typo due to the momentum scaling), and so the corrected version of the minimum optimal learning rate is actually 30,000 / 128^2 ≈ 1.8. It's also probably important to note that VGG is a bit higher based on the plot - close to 3 here.

Here is the corrected version of Appendix Figure 4:
![image](https://user-images.githubusercontent.com/13008542/52883216-29291a80-3138-11e9-8294-009a9aa23d87.png)

Again, thanks for catching the error and please let us know if there are any more errors.

Wesley

**Comment by devmotion** [comment]
Hi,

Thanks for your quick and detailed reply! I should mention that actually my supervisor Fredrik Lindsten spotted that error first and brought it up in our discussion. :slightly_smiling_face: 

David

**Comment by wjmaddox** [comment]
I'm closing this now that I've updated the code: https://github.com/wjmaddox/swa_gaussian/commit/b97b40cf9195a43176868aa0d4a289867ba7a83d

Thanks again for bringing it to our attention.

**Comment by wjmaddox** [comment]
Thanks again for noticing that issue - I put your name in the acknowledgements in the final version on arxiv.

Cheers,
Wesley

**Comment by devmotion** [comment]
Thanks!
